### ISSUE TITLE
Set up TravisCI to cache its local Maven repo

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/butterfly#128]
Set up TravisCI to cache its local Maven repo. That will make builds much faster, since there will be no need to download the whole UNIVERSE for every single build.

**Comment by fabiocarvalho777** [comment]
@mmcrockett @spetratos if you plan to release Butterfly soon, then fix this issue here first, otherwise you won't be able to deploy it to Maven Central.

**Comment by spetratos** [comment]
That's on my list of things to do. Will looks at it tomorrow.


Sp


________________________________

**Comment by fabiocarvalho777** [comment]
Thanks Spiros.
