### ISSUE TITLE
Release 2.4.0 includes 2.5.0-SNAPSHOT elements.

### ISSUE THREAD

**Issue by mmcrockett** [paypal/butterfly#136]
@fabiocarvalho777 Just noticed the CLI Packaged zip for 2.4.0 includes 2.5.0-SNAPSHOT elements. This needs to be investigated to ensure it doesn't happen again.

How to reproduce:
Download 'https://search.maven.org/remotecontent?filepath=com/paypal/butterfly/butterfly-cli-package/2.3.0/butterfly-cli-package-2.3.0.zip'
Run 'unzip -l butterfly-cli-package-2.3.0.zip | grep SNAP' and see no results.

Now:
Download 'https://search.maven.org/remotecontent?filepath=com/paypal/butterfly/butterfly-cli-package/2.4.0/butterfly-cli-package-2.4.0.zip'
Run 'unzip -l butterfly-cli-package-2.4.0.zip | grep SNAP' and see that there are several 2.5.0-SNAPSHOT artifacts.

**Comment by fabiocarvalho777** [comment]
I don't know of the top of my head, I would have to investigate it. Most of versions are managed, they are not set explicitly, so this sounds very weird to me.

**Comment by mmcrockett** [comment]
Didn't have this problem in the 2.5.0 release so maybe just a one time error. Closing.
