### ISSUE TITLE
JavaMatch should automatically ignore package-info.java files

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/butterfly#179]
`com.paypal.butterfly.utilities.conditions.java.JavaMatch` TU should by default automatically ignore (skip evaluation) `package-info.java` files, returning a warning ([similar to this](https://github.com/paypal/butterfly/blob/master/butterfly-utilities/src/main/java/com/paypal/butterfly/utilities/conditions/java/JavaMatch.java#L113)) with `false` as value by default, but stating that the specified Java file is a `package-info` file.

Make that value configurable though, by adding a boolean property called `packageInfo`. Its default value should be `false`, and it should have a getter and setter.

Add unit test as well, covering default value, and setting that to false, or true.

**Comment by fabiocarvalho777** [comment]
@amriteya hey Amirit, this is the next issue for you. Let me know if you have any questions.

**Comment by amriteya** [comment]
@fabiocarvalho777 Fabio, what according to you would be the best check for `package-info` file. I am inclined towards String match on the filename for checking whether the file is a `package-info.java` file.

There are other ways where we could look up the `CompilationUnit` for `PackageDeclaration` and `ImportDeclaration`. However, acc to the JLS, this check might not be exhaustive.
Reference: [Packages > Named Packages](https://docs.oracle.com/javase/specs/jls/se7/html/jls-7.html#jls-7.4.1)

Even though there is a best practice defined, there is no rule that the package-info.java file should only contain package declarations and import declarations. It could contain source code.

**Comment by fabiocarvalho777** [comment]
@amriteya all good points Amrit. And I agree with you, for now it makes more sense to rely on the file name only, as long as we explain that clearly in our API.

Thanks by the way for opening that issue with JavaParser, I see they answered pretty quickly.
