### ISSUE TITLE
Vague IllegalArgumentException if "version to" is older than current version

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/butterfly#214]
In the case of an upgrade, [this IllegalArgumentException](https://github.com/paypal/butterfly/blob/master/butterfly-core/src/main/java/com/paypal/butterfly/core/UpgradePath.java#L62-L64) is thrown if "version to" is older than current version.

That `if` statement and the exception it throws should be replaced by these more specific verifications:

1. Check if the requested version is inexistent, and throw a `IllegalArgumentException` saying "The requested upgraded version is inexistent".
1. Check if the requested version is the same as the current one, and throw a `IllegalArgumentException` saying "The requested upgrade version is the same as the version the application is currently at".
1. Check if the requested version is older than the current one, and throw a `IllegalArgumentException` saying "The requested upgrade version is older than the version the application is currently at".

**Comment by badalsarkar** [comment]
Hi @fabiocarvalho777 
I can work on this issue.

Thanks,

**Comment by fabiocarvalho777** [comment]
@badalsarkar please go ahead. Notice I fixed the broken link above and also enhanced the description of the. Please read it again and let me know if you have questions. Thanks.

**Comment by badalsarkar** [comment]
Hi @fabiocarvalho777 ,

I am getting this error while running `gradlew test`. The error occurs after I run the command couple of times. The first time I got the message `heap space error`. I am not sure how to fix it with gradle. I looked into [this](https://github.com/gradle/gradle/issues/12436) GitHub issue. As mentioned there, if I restart my pc the problem temporarily goes away. Have any idea how to solve it?

```bash
(issue-214 U:1 ?:2 ✗) butterfly ./gradlew test

FAILURE: Build failed with an exception.

* What went wrong:
Cannot create service of type TaskExecuter using ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #21 of type ReservedFileSystemLocationRegistry.
> Cannot create service of type ReservedFileSystemLocationRegistry using ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by fabiocarvalho777** [comment]
No, I have never seen this issue. I read the GitHub issue you shared, it looks like the problem could be related to having more than one Gradle daemon running at the same time in your laptop, and that would explain why rebooting it would solve it.

**Comment by badalsarkar** [comment]
The `UpgradeStep` has `getNextVersion()` to query the next version. So far what I have found is that there is no method to query the previous versions. To check if the requested version is older than current version, I would like to use [`VersionNumber`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/util/VersionNumber.java) class from [`Gradle-Core`](https://mvnrepository.com/artifact/org.gradle/gradle-core/6.1.1). 

If that is alright how should I add it in the [`build.gradle`](https://github.com/paypal/butterfly/blob/master/butterfly-core/build.gradle)?

**Comment by badalsarkar** [comment]
> The `UpgradeStep` has `getNextVersion()` to query the next version. So far what I have found is that there is no method to query the previous versions. To check if the requested version is older than current version, I would like to use [`VersionNumber`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/util/VersionNumber.java) class from [`Gradle-Core`](https://mvnrepository.com/artifact/org.gradle/gradle-core/6.1.1).
> 
> If that is alright how should I add it in the [`build.gradle`](https://github.com/paypal/butterfly/blob/master/butterfly-core/build.gradle)?

I think I found it. I should add it [here](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/build.gradle#L222)

**Comment by fabiocarvalho777** [comment]
Issue solved. Thank you very much @badalsarkar !!! :-)
