### ISSUE TITLE
CLI should never (or very rarely) output the string 'null'

### ISSUE THREAD

**Issue by crankydillo** [paypal/butterfly#350]
If the appropriate CLI arguments aren't specified, the upgrade version is displayed as 'null' from [this LoC](https://github.com/paypal/butterfly/blob/6dbb5f8ccfa91c59bd98a7526dd86ffbb473cee1/butterfly-cli/src/main/java/com/paypal/butterfly/cli/ButterflyCliRunner.java#L201).  Some alternatives for dealing with this:

- Require the CLI argument
- Don't require it, but default it to something (LATEST, UNSPECIFIED, etc.)
- Don't require it, but handle it in the code somehow (e.g. just output LATEST, UNSPECIFIED, etc. if null)

I think I like the second option.

Update: Added link

**Comment by fabiocarvalho777** [comment]
Sorry, Sam, but ths issue isn't clear. You forgot to add the link. Also, regardless of the link, I am not sure what you are referring to. Could you provide sample steps to reproduce it and sample output? Thanks!!

**Comment by crankydillo** [comment]
Hey Fabio,  this is the problematic output:
```sh
Performing upgrade from version 3.10.1 to version null (it might take a few seconds)
```
I can't give you exact reproducible, but I believe you get it if you just use:
```sh
butterfly path-to-project
```
I added the link above.  To be honest, that was the key part that I was hoping would explain things.  Sorry I missed it.

**Comment by fabiocarvalho777** [comment]
Thanks!! Obviously this isn't required, but if you feel like fixing this that would be very much appreciated. Thanks again.
