### ISSUE TITLE
No registered extensions

### ISSUE THREAD

**Issue by nikos912000** [paypal/butterfly#354]
Hi there :wave:

Nice project!

I'm following the Quick Start docs but haven't managed to install any extensions.

I've copied the `butterfly-springboot-extension-3.0.0.jar` jar into the `extensions` dir but still getting the following:

```
There are no registered extensions
```

## Specs
I'm on MacOS Mojave and have tried to install both with brew and with the zip file.
Also, using AdoptOpenJDK's Java and tried with different versions (8, 13, etc.).

Any ideas?

**Comment by fabiocarvalho777** [comment]
Hello,
Let me check, I will get back to you in a minute.

**Comment by fabiocarvalho777** [comment]
There is a problem with that sample extension zip file. It is actually empty. Let me see if I can correct that quickly.

**Comment by fabiocarvalho777** [comment]
Ok, I believe I have corrected the problem now. Please try to download the sample extension again using the same link (from the document) you used before.

Please let me know how it goes. I am going to close this issue, and consider it resolved, but if it doesn't work for you I can reopen it, just let me know.

Thanks for reporting this issue.

**Comment by fabiocarvalho777** [comment]
I just noticed the Quick start guide also needed some changes. I have just updated it. However, it takes some time for the web app to sync with latest changes. Because of that, [please read it directly from the md file here](https://github.com/paypal/butterfly/blob/master/docs/QUICK_START.md).

**Comment by nikos912000** [comment]
Thanks, looks ok now :)

**Comment by fabiocarvalho777** [comment]
Awesome! Please feel free to share any feedback, report any bug, or contribute with code changes too :-)
