### ISSUE TITLE
Butterfly should allow numbers in the extension property names

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/butterfly#359]
According to [Butterfly CLI help](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/butterfly-cli/src/main/java/com/paypal/butterfly/cli/ButterflyCliOption.java#L88), Butterfly should allow numbers in the extension property names.
However, it does not, [as seen here](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/butterfly-core/src/main/java/com/paypal/butterfly/core/ConfigurationImpl.java#L27).

The first character must be alphabetic only, and the others maybe alphabetic, numeric, dot, underscore or hyphen.

This is a bug, and should be fixed.

**Comment by himanshugoyal1065** [comment]
Hi @fabiocarvalho777, 
I'll like to take up this issue. :)

**Comment by fabiocarvalho777** [comment]
Sure, go for it, please. :-)

**Comment by himanshugoyal1065** [comment]
Hi @fabiocarvalho777,
I tried installing Butterfly via brew but got an error(the repo is archived so can't really open an issue there)

![image](https://user-images.githubusercontent.com/42549653/95113228-c0a10e00-075f-11eb-9666-ae894e3cb409.png)

TIA :)

**Comment by fabiocarvalho777** [comment]
Hello,
I have just unarchived the repo. Could you try again and let me know, please?
Thanks.

**Comment by fabiocarvalho777** [comment]
Hey @himanshugoyal1065 ,

To unblock you, until we solve the brew problem, please install Butterfly CLI using the zip file.
The instructions are here, under section [https://paypal.github.io/butterfly/Installing-Butterfly](https://paypal.github.io/butterfly/Installing-Butterfly).

Thanks.

**Comment by fabiocarvalho777** [comment]
Hello @himanshugoyal1065 . Just checking, are you still working on this issue? Thanks.

**Comment by himanshugoyal1065** [comment]
Hello @fabiocarvalho777, 
TBH I'm still not able to install butterfly locally. I might need your help in this. I'll message you personally regarding this, if you don't mind :)

**Comment by fabiocarvalho777** [comment]
No, problem. You can contact me at fabiocarvalho777@gmail.com.
By the way, the best way to develop and test your code changes when adding a new feature or fixing a bug is by running Butterfly from your IDE, as explained in the bottom of [this document](https://paypal.github.io/butterfly/Extension-development-guide).

**Comment by himanshugoyal1065** [comment]
Thank you so much. I'll reach out to you on slack as I work for PayPal only :)
Awesome. I'll try running it on my IDE and see how it goes. 
Thanks again for all your help.

**Comment by fabiocarvalho777** [comment]
Oh ok, slack sounds good :-)

**Comment by VietnameZe** [comment]
Can I try this one?

**Comment by badalsarkar** [comment]
Hi Fabio,
I looked at [this](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/butterfly-core/src/test/java/com/paypal/butterfly/core/ButterflyFacadeImplTest.java#L91-L101) test. Should [line 93](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/butterfly-core/src/test/java/com/paypal/butterfly/core/ButterflyFacadeImplTest.java#L93) be a valid property name as asserted in the test? Reading the comments [here](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/butterfly-core/src/main/java/com/paypal/butterfly/core/ConfigurationImpl.java#L37-L48) and [Butterfly CLI Help](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/butterfly-cli/src/main/java/com/paypal/butterfly/cli/ButterflyCliOption.java#L88), it seems to me that it should be invalid.

Please correct me if I am missing something.

**Comment by fabiocarvalho777** [comment]
Hello Badal,

> I looked at this test. Should line 93 be a valid property name as asserted in the test? 

You are right, it should not be considered valid. It should be in that array in line 100 but it is not. You caught a bug, thanks! Would you mind fixing it as part of this issue, please? Thanks.

Also, regarding [this comment](https://github.com/paypal/butterfly/blob/d7c9819de9e7516d32950b2348c71b9d424d691a/butterfly-core/src/main/java/com/paypal/butterfly/core/ConfigurationImpl.java#L47), it doesn't say numbers are also valid, nor that the very first character must be alphabetic. Would you mind changing that comment, please? Here is the rule we want to establish: `The first character must be alphabetic only, and the others maybe alphabetic, numeric, dot, underscore or hyphen`.

I hope that helps, let me know if you have other questions, and thanks for catching all these details!!

**Comment by badalsarkar** [comment]
I will do. Thanks you. :smile:

**Comment by fabiocarvalho777** [comment]
@badalsarkar thank you very much for your contribution!! :-)
