### ISSUE TITLE
support extensions packaged as spring-boot uber jar

### ISSUE THREAD

**Issue by myohn-paypal** [paypal/butterfly#364]
Add support for loading butterfly extension jars that are packaged as spring-boot uber jar.

To make it easier for an extension to include its own transitive depdencies, change butterfly so that it can load extension jars that contain nested jars created by spring-boot maven plugin.

**Comment by fabiocarvalho777** [comment]
That is a good feature request. It will require classpath isolation though, not a very trivial problem to solve.

**Comment by myohn-paypal** [comment]
Yes, this issue is for allowing _more_ dependencies to be easily added.
Classloader isolation will be done in a separate issue / pull request.

**Comment by fabiocarvalho777** [comment]
So, you mentioned classpath isolation will be done in a separated PR. With the current changes you provided, what happens if there are two extensions installed, and they both use the same library, but in different versions? Wouldn't that cause a conflict?

**Comment by myohn-paypal** [comment]
With current changes: yup, there would be a conflict if the extension brought in a mismatched version of an existing dependency. It'd just be like placing inconsistent jars on the classpath. The first jar would win and the class would be loaded from there. There is a chance of linkage errors like NoSuchMethodError being thrown.

(In fact, I think butterfly itself has internally inconsistent dependencies. The build should be configured with [maven dependency convergence rule](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) or its [gradle equivalent](https://kordamp.org/enforcer-gradle-plugin/#_dependencyconvergence)

The intent here with this pull request is that the extension can more easily add additional dependencies by dropping a single jar. The extension creator or butterfly deployer still has to be careful in ensuring consistent dependencies.

&nbsp;
With classloader isolation later on, hopefully such problems can be reduced.

**Comment by fabiocarvalho777** [comment]
Ok, thanks.
